// examples/vue/src/App.vue
<script setup lang="ts">
 import { ref } from 'vue'
 const count = ref(0)
</script>

<template>
  <div>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <button type="button" @click="count++">count is {{ count }}</button>
  <hr />
  <button type="button" @click="$userback.show()">Show</button>
  <button type="button" @click="$userback.hide()">Hide</button>
  <hr />
  <button type="button" @click="$userback.open('bug')">Open Bugs</button>
  <button type="button" @click="$userback.open('general', 'screenshot')">Screenshot me!</button>

</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// examples/react-class/src/App.tsx
import React from 'react';
import { withUserback } from '@userback/react';
import reactLogo from './react.svg';

// @TODO: Fix Typescript prop types and count prop
// eslint-disable-next-line react/prefer-stateless-function
class App extends React.Component {
    render() {
        return (
            <div className="App">
                <div>
                    <a href="https://reactjs.org" target="_blank" rel="noreferrer">
                        <img src={reactLogo} className="logo react" alt="React logo" />
                    </a>
                </div>
                <h1>Vite + React Class</h1>
                <div className="card">
                    {/* <button type="button" onClick={() => setCount((c) => c + 1)}> */}
                    {/*     <span>count is: </span> */}
                    {/*     {count} */}
                    {/* </button> */}
                    <hr />
                    <button type="button" onClick={() => this.props.userback.open('bug')}>Open Bugs</button>
                    <button type="button" onClick={() => this.props.userback.open('general', 'screenshot')}>Screenshot me!</button>
                    <hr />
                    <button type="button" onClick={() => this.props.userback.hide()}>Hide</button>
                    <button type="button" onClick={() => this.props.userback.show()}>Show</button>
                </div>
            </div>
        );
    }
}

export default withUserback(App);
