// examples/vue2/src/App.vue
<template>
  <div id="app">
  <div>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <hr />
  <button type="button" v-on:click="$userback.show()">Show</button>
  <button type="button" v-on:click="$userback.hide()">Hide</button>
  <hr />
  <button type="button" v-on:click="$userback.open('bug')">Open Bugs</button>
  <button type="button" v-on:click="$userback.open('general', 'screenshot')">Screenshot me!</button>
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// examples/react/src/App.tsx
import { useState } from 'react';
import reactLogo from './assets/react.svg';
import './App.css';
import { useUserback } from '@userback/react';

function App() {
    const [count, setCount] = useState(0);
    // Get Userback hooks
    const { show, hide, open } = useUserback()

    return (
        <div className="App">
            <div>
                <a href="https://reactjs.org" target="_blank">
                    <img src={reactLogo} className="logo react" alt="React logo" />
                </a>
            </div>
            <h1>Vite + React</h1>
            <div className="card">
                <button onClick={() => setCount((count) => count + 1)}>count is {count}</button>
                <hr />
                <button onClick={() => open('bug')}>Open Bugs</button>
                <button onClick={() => open('general', 'screenshot')}>Screenshot me!</button>
                <hr />
                <button onClick={() => hide()}>Hide</button>
                <button onClick={() => show()}>Show</button>
            </div>
        </div>
    );
}

export default App;
