// examples/vue2/src/App.vue
<script>
export default {
  data() { return { count: 0 }  },
  methods: {
    increment() { this.count += 1 }
  }
}
</script>

<template>
  <div id="app">
  <div>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <button @click="increment">{{count}}</button>
  <hr />
  <button type="button" v-on:click="$userback.show()">Show</button>
  <button type="button" v-on:click="$userback.hide()">Hide</button>
  <hr />
  <button type="button" v-on:click="$userback.open('bug')">Open Bugs</button>
  <button type="button" v-on:click="$userback.open('general', 'screenshot')">Screenshot me!</button>
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// react-test/src/App.tsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import './App.css'
import Userback from 'userback-react'

function App() {
  const [count, setCount] = useState(0)
  return (
    <div className="App">
      <Userback />
      <div>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
    </div>
  )
}

export default App
